# Exercises

In [1]:
import numpy as np
import pandas as pd
import viz

1.) How likely is it that you roll doubles when rolling two dice?

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[5, 5],
       [6, 2],
       [1, 5],
       ...,
       [4, 2],
       [6, 5],
       [4, 6]])

In [3]:
#restting simulations with transpose
rolls_transposed = rolls.transpose()
rolls_transposed

array([[5, 6, 1, ..., 4, 6, 4],
       [5, 2, 5, ..., 2, 5, 6]])

In [4]:
(rolls_transposed[0] == rolls_transposed[1]).mean()

0.17

# Exercise 2

2.) If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# 1 = heads 0 = tales
simulation = nrows = 10**5
coins_flipped = ncols = 8

flips = np.random.choice([0,1], size = (nrows, ncols))
flips

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 0, 1]])

In [6]:
# sum of how many times 1 (heads) was landed on in a row
# this is done by using 0 and 1 for example:
# if it lands on heads (1) and then tails (0)
# it adds 1 + 0 = 1 (out of 2 columns).
# this is continued until the ncols (number of columns) 8 is reached

flip_action = flips.sum(axis = 1)
flip_action

array([5, 3, 3, ..., 3, 5, 5])

In [7]:
# exactly 3 heads
flipped_heads = flip_action == 3
flipped_heads.mean()

0.21989

In [8]:
# more than 3 heads/3 or more heads
extra_flipped_heads = flip_action > 3
extra_flipped_heads.mean()

0.63618

# Exercise 3

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [9]:
# datascience alumni = 0 web devs = 1
two_billboards = nrows = 2
simulations = 10_000

# 4 split 4 ways. Each number is independent
ds_probability = 0.25
webdev_probability = 0.75


In [10]:
first_billboard = np.random.choice([0,1], size = (simulations, two_billboards),
                                   p=[webdev_probability, ds_probability])

second_billboard = np.random.choice([0,1], size = (simulations, two_billboards),
                                   p=[webdev_probability, ds_probability])


In [11]:
data = (first_billboard == [0,0]) & (second_billboard == [0,0])
data.mean()

0.56065

# Exercise 4

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [12]:
# loc for avg and scale for stddev

n_simulations = n_rows = 10_000
n_days = n_columns = 5

simulation = np.random.normal(loc = 3, scale = 1.5, size = (n_rows, n_columns)).round()
simulation = np.where(simulation < 0, 0, simulation)
simulation 

array([[ 4.,  5.,  2.,  3.,  5.],
       [ 4.,  4.,  2.,  4.,  1.],
       [ 2.,  2.,  4.,  0.,  3.],
       ...,
       [ 1.,  3.,  4.,  0.,  3.],
       [ 2.,  1., -0.,  2.,  3.],
       [ 3.,  3.,  3.,  4.,  3.]])

In [13]:
num_of_poptarts = simulation.sum(axis = 1)
num_of_poptarts

array([19., 15., 11., ..., 11.,  8., 16.])

In [14]:
if_poparts_avail = num_of_poptarts < 17
if_poparts_avail.mean()

0.6715

# Exercise 5

Compare Heights : 
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [15]:
n_simulations= nrows = 10_000
m_height = np.random.normal(loc = 178, scale = 8, size = nrows)
f_height = np.random.normal(loc = 170, scale = 6, size = nrows)

In [16]:
female_taller_than_male = f_height > m_height
female_taller_than_male.mean()

0.2098

# Exercise 6

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fail:

- What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [17]:
n_simulations = n_rows = 10_000
n_students = n_columns = 50 

failed_install = np.random.choice([1,0], size = (n_rows, n_columns), p=[1/250, 249/250])

In [18]:
no_fails = failed_install.sum(axis = 1) < 1
no_fails.mean()

0.8145

- 100 students?

In [19]:
n_simulations = n_rows = 10_000
n_students = new_columns = 100

failed_install = np.random.choice([1,0], size = (n_rows, new_columns), p=[1/250, 249/250])
no_fails = failed_install.sum(axis = 1) < 1
no_fails.mean()

0.6698

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [20]:
n_simulations = n_rows = 10_000
n_students = new_columns = 150

failed_install = np.random.choice([1,0], size = (n_rows, new_columns), p=[1/250, 249/250])
no_fails = failed_install.sum(axis = 1) > 0
no_fails.mean()

0.4577

- How likely is it that 450 students all download anaconda without an issue?

In [21]:
n_simulations = n_rows = 10_000
n_students = new_columns = 450

failed_install = np.random.choice([1,0], size = (n_rows, new_columns), p=[1/250, 249/250])
no_fails = failed_install.sum(axis = 1) < 1
no_fails.mean()

0.1643

# Exercise 7

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [22]:
nrows = 10_000
ncols = 3

trucks = np.random.choice([1,0], size =(nrows, ncols), p =[0.7, 0.3])
(trucks.sum(axis=1)==0).mean()

0.0312

In [23]:
ncols = 2

trucks = np.random.choice([1,0], size = (nrows, ncols), p=[0.7,0.3])
(trucks.sum(axis=1)>0).mean()

0.9106

# Exercise 8

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [24]:
simulations = np.random.randint(1, 366, size = (10_000, 23))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 23).mean() #23 people

0.5067

In [25]:
simulations = np.random.randint(1, 366, size = (10_000, 20))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 20).mean() #20 people

0.4143

In [26]:
simulations = np.random.randint(1, 366, size = (10_000, 40))
simulations = pd.DataFrame(simulations)
(simulations.apply(lambda birthdays: birthdays.nunique(), axis=1) < 40).mean() #40 people

0.8942